//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УчебнаяПрактика1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grafik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grafik()
        {
            this.Sotrydnik = new HashSet<Sotrydnik>();
        }
    
        public int id_grafik { get; set; }
        public System.DateTime DateOfMonth { get; set; }
        public int Hour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrydnik> Sotrydnik { get; set; }
    }
}
